//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rumeysabukecik_com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Blog_Kategori
    {
        public int ID { get; set; }
        public short BlogID { get; set; }
        public short KategoriID { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
