//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public short NotID { get; set; }
        public Nullable<int> Not1 { get; set; }
        public Nullable<int> Not2 { get; set; }
    }
}
