//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int OgretmenID { get; set; }
        public string OgretmenAdi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    }
}
